### PR TITLE
Update tracing to work with newer semconv and zipkin

### PR DESCRIPTION
**Pull request by harshitgarg22**
This updates the go.mod file in tracing and source code to work with newer version of zipkin and semconv. Needed for https://github.com/ease-lab/vSwarm/runs/6114640539?check_suite_focus=true

### CODE REVIEW

**Comment by ustiugov** [comment]
That looks good! Could you please check if you can see the traces properly for one of the workloads? Eg chain serving with docker-compose would be enough

**Comment by dhschall** [comment]
Yea looks good 👍 
And good idea from Dmitrii to check the trace output.
You know how to do right?

**Review by dhschall — APPROVED** [review]

**Comment by ustiugov** [comment]
Python tracing files are broken. Can you check?

**Comment by harshitgarg22** [comment]
That is because the protobuf file path is not correct for integ-tests in go.mod. This is changed in the `add-relay` branch where for relay we start using `vSwarm-proto` repo for helloworld instead of the local one.

**Review by ustiugov — APPROVED** [review]

**Comment by ustiugov** [comment]
thanks for the explanation, I see. however, this means that you should have first introduced vSwarm-proto in a separate PR and merged it. Please plan the order of PRs more carefully next time so there are no broken tests

**Pull request merged**
