### PR TITLE
Add input structure support to relay

### PR DESCRIPTION
**Pull request by harshitgarg22**
- Adds support for specifying [`Input`](https://github.com/ease-lab/vSwarm-proto/blob/main/grpcclient/grpcclient.go#L26) parameters from relay shell arguments
- Updates relay README to specify debugging procedure
- Adds relay CI test

### CODE REVIEW

**Comment by harshitgarg22** [comment]
@ustiugov https://github.com/ease-lab/vSwarm/runs/6193597345?check_suite_focus=true#step:7:12
Can you see if this is due to some docker credential access problem?

**Comment by ustiugov** [comment]
Please request my review after all David's feedback is satisfied. I cannot keep up with all the reviews and you may risk waiting for hours or days unnecessarily.

I think you missed the docker log in part

**Comment by harshitgarg22** [comment]
> I think you missed the docker log in part

I'm not sure I understand? Do you know why `docker push` isn't working on CI? It works locally.

**Review by dhschall — APPROVED** [review]

**Review by dhschall — COMMENTED** [review]
Wait that was incorrect.
I think we should do it a bit differnt but Ill discuss this quickly with you

**Review by dhschall — COMMENTED** [review]
@harshitgarg22 please check if that makes sense.
I tagged now the proto repo that there will be no dependency problems at some point

**Review by dhschall — APPROVED** [review]

**Review by dhschall — APPROVED** [review]

**Pull request merged**
