### PR TITLE
Change go tracing module from vhive to vSwarm

### LINKED ISSUE #51: Change go tracing module from vhive to vSwarm
**Describe the bug**
The tracing go module in `utils/tracing/go/go.mod` is named `github.com/ease-lab/vhive/utils/tracing/go`
change vhive to vSwarm to keep everything here.

Then change also all benchmarks to use this module instead of the vhive repo

### PR DESCRIPTION
**Pull request by dhschall**
Fixes #51

### CODE REVIEW

**Comment by ustiugov** [comment]
@dhschall can you please use `grep` to see if any code in this repo has the same stale dependency?

**Comment by dhschall** [comment]
Need to fix #92 first to make everything really clean

**Review by ustiugov — APPROVED** [review]
please merge asap after the runners are fixed

**Comment by ustiugov** [comment]
@dhschall please go ahead with merging

**Comment by ustiugov** [comment]
@dhschall when are we merging this one?

**Comment by harshitgarg22** [comment]
I did not realize that there was another PR fixing tracing module naming. I have made some changes in relay branch also for this. If this is complete please merge it into main asap. Otherwise my changes are also working.

**Comment by ustiugov** [comment]
@harshitgarg22 please rebase and see if your PR missed anything

**Comment by dhschall** [comment]
Sorry for missing this thread.
Can I still merge the PR?

**Comment by ustiugov** [comment]
Harshit started to fix it in another pr that we merged today.

**Comment by dhschall** [comment]
Ok great.
Then Ill archive this PR

**Comment by ustiugov** [comment]
No, just leave it to Harshit. He needs to check if there is anything he missed in the previous pr

**Comment by harshitgarg22** [comment]
I have merged the changes into add-relay here https://github.com/ease-lab/vSwarm/pull/118/commits/af89a183b7c4b9e1a4baad98af6a6c1e5f68b24d.
It should be fine to close this then I guess.

**Comment by ustiugov** [comment]
Ok but don't merge unrelated features in a single PR in future, this creates a mess

**Pull request merged**
