### PR TITLE
Add online shopping

### PR DESCRIPTION
**Pull request by harshitgarg22**
Adds online shopping benchmark as part of the standalone benchmark suite.
Adds:
- [x] docker compose yamls for all services
- [x] knative yamls for all services

### CODE REVIEW

**Review by dhschall — CHANGES_REQUESTED** [review]
I think you do not need to commit this file
benchmarks/online_shop/adservice/lightstep-opentelemetry-javaagent-0.8.1.jar
Its very large and also [they](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/adservice) dont commit it.

Also Im not sure if the Gopkg lock files are required:
[benchmarks/online_shop/shippingservice/Gopkg.lock](https://github.com/ease-lab/vSwarm/pull/103/files#diff-1e48236dd30143cc51caab38185be6311ab8a53df26b9d12bd5ac2721614e8ed)

**Comment by dhschall** [comment]
@ustiugov for you to understand why there are so many files and why I made a last commit.
All files in the xxxservice subfolders are exactly the one taken from the online boutique example release version v0.3.6.
I just updated yesterday all source files to the very last official release version from them and checked if everything still works.
Furthermore I added a 
- README explaining exactly where we the sources come from
- A small helper script that people can use to update the source files to a specific version

**Review by dhschall — APPROVED** [review]

**Comment by dhschall** [comment]
@harshitgarg22 I fixed now the things for knative.
However, the tests did not run today properly Ill start them tomorrow again and the hopefully we can merge this PR as well

**Comment by ustiugov** [comment]
> Question @ustiugov 
> 
> We use the original sources from googles online shop examples.
> 
> However, for them they have a few linting problems. Do we want to exclude it from linting, fix the linting or ignore it as with the chained functions?
> 
> 

Since we are not going to keep those sources in sync with upstream, I suggest fixing linting errors if they are not so many. If they are many, I am ok with exclusion

**Comment by dhschall** [comment]
So I checked the linting and its not a quick fix. It seems to be only a few things to two things are deprecated packages. When I wanted to update them to new packages I realized they have another interface.
Therefore, I disabled now the linting for this benchmarks and Ill keep an eye on the upstream repo. With the script I added to directory its easy to update to next version

**Pull request merged**
